### PR TITLE
apt-get (not pip) install SciPy

### PR DESCRIPTION
**Pull request by larsmans**
Hopefully this will prevent timeouts on Travis.

### CODE REVIEW

**Comment by kmike** [comment]
I'm now using this setup to install numpy&scipy for Python 2.x and 3.x on Travis: https://github.com/TeamHG-Memex/Formasaurus/blob/master/.travis.yml. scipy is still installed by pip (it is in install_requires); apt-get install scipy ensures dependencies are satisfied. It is kind of slow the first time (and with no output because of travis_wait), but subsequent runs are fast.

**Comment by larsmans** [comment]
Thanks, I stole some of that for my second version. I'm now trying Travis's [Trusty beta](http://docs.travis-ci.com/user/trusty-ci-environment/) to get a new enough SciPy.

**Comment by kmike** [comment]
wow, they finally made Trusty beta, didn't know that - thanks!

**Comment by larsmans** [comment]
Not that it matters, it doesn't seem to pick up the right NumPy for some reason...

**Comment by larsmans** [comment]
Ok, got it right, pushed to master.

**Comment by kmike** [comment]
:+1:

**Pull request merged**
